### ISSUE TITLE
Unable to add multiple printers via setup wizards

### ISSUE THREAD

**Issue by bob-koertge** [fr3ak2402/GalaxySlicer#12]
**Describe the bug**

**3mf File for This Bug**
If it is related to slicing, please append the 3mf file. It could be extremely helpful to solve the issue.

**To Reproduce**

1. Select Creality  K1 .4mm Printer
2. Select Prusa MK3S .4, .6. 8 Printers

**Expected behavior**
All selections shown in application.

**Screenshots**

**Printer model**

**Desktop (please complete the following information):**
Windows 11

**Comment by fr3ak2402** [comment]
Thank you very much for the bug-report.

I was able to fix the problem.

If you want to temporarily fix the problem in your installed version of Slicer. You can replace the folder and file in the zip file with those in your installation folder.

The folder and file are in the `resources/profiles` folder.

[Prusa.zip](https://github.com/fr3ak2402/GalaxySlicer/files/12105539/Prusa.zip)
