### ISSUE TITLE
MacOS Version not supported

### ISSUE THREAD

**Issue by xDarkOverlordx** [fr3ak2402/GalaxySlicer#14]
This is not supported on Ventura OS. Thanks for the hard work!

**Comment by xDarkOverlordx** [comment]
Sorry, to clarify, I'm using MacOS Intel based not M1 or M2.

**Comment by fr3ak2402** [comment]
We are working on releasing a version of GalaxySlicer for macOS x64 (Intel Mac).

**Comment by xDarkOverlordx** [comment]
Awesome, can't wait

**Comment by jyang-wemade** [comment]
Running M1 Mac Studio, alpha 2 gives the message 
![image](https://github.com/fr3ak2402/GalaxySlicer/assets/52301754/337aa3e2-5fd3-41e4-b1a4-34c5a797a449)

**Comment by fr3ak2402** [comment]
@jyang-wemade 

https://github.com/fr3ak2402/GalaxySlicer/wiki/Install-on-macOS

**Comment by jyang-wemade** [comment]
Thanks.  My apologies for not reading the wiki.  Works now.
