### ISSUE TITLE
Unable to find Alpha2 for download

### ISSUE THREAD

**Issue by kaushikbm** [fr3ak2402/GalaxySlicer#24]
Getting a 404 when trying to download from the links in my mail. And unable to find any Releases or Tags in the repository !

**Comment by kaushikbm** [comment]
Great ! Able to see the updated repository now. But windows asset is missing.

**Comment by fr3ak2402** [comment]
The Windows version of the alpha2 will be added later, because I'm finishing a hotfix for this version.

**Comment by fr3ak2402** [comment]
You can now also download the Windows version

**Comment by kaushikbm** [comment]
Thank you for the upload. Very much excited.
