### ISSUE TITLE
Unable to setup Alpha2 release

### ISSUE THREAD

**Issue by kaushikbm** [fr3ak2402/GalaxySlicer#26]
The Setup Wizard keeps coming back and doesn't retain any setup parameters.

![image](https://github.com/fr3ak2402/GalaxySlicer/assets/5709898/d986a805-71a4-4636-b1af-f72be31b6154)

Even after selecting the printer only the defaults are available. (Mine is a Creality K1)

![image](https://github.com/fr3ak2402/GalaxySlicer/assets/5709898/632df551-13f1-4816-a153-7a89ff50c8c6)

OS : Windows 11

Note : Alpha release was having no such issue.

**Comment by fr3ak2402** [comment]
Download the Hotfix

**Comment by kaushikbm** [comment]
Hotfix solved the issue.
Thanks !
