### ISSUE TITLE
mac mini m2 crash

### ISSUE THREAD

**Issue by vivikuyo** [fr3ak2402/GalaxySlicer#27]
-------------------------------------
Translated Report (Full Report Below)
-------------------------------------

Process:               GalaxySlicer [79628]
Path:                  /Applications/GalaxySlicer.app/Contents/MacOS/GalaxySlicer
Identifier:            com.tji.galaxy-slicer
Version:               1.0.0-alpha2 (???)
Code Type:             ARM-64 (Native)
Parent Process:        launchd [1]
User ID:               501

Date/Time:             2023-08-01 21:14:18.5707 +0800
OS Version:            macOS 13.4.1 (22F770820d)
Report Version:        12
Anonymous UUID:        A3C956F4-9413-374D-1114-E0CC7FBD6F92

Time Awake Since Boot: 590000 seconds

System Integrity Protection: enabled

Crashed Thread:        0

Exception Type:        EXC_CRASH (SIGABRT)
Exception Codes:       0x0000000000000000, 0x0000000000000000

Termination Reason:    Namespace DYLD, Code 1 Library missing
Library not loaded: /opt/homebrew/*/libssh2.1.dylib
Referenced from: <D8DFF0E4-8FD8-367B-A108-36D28C92FABF> /Applications/GalaxySlicer.app/Contents/MacOS/GalaxySlicer
Reason: tried: '/opt/homebrew/*/libssh2.1.dylib' (no such file), '/System/Volumes/Preboot/Cryptexes/OS/opt/homebrew/*/libssh2.1.dylib' (no such file), '/opt/homebrew/*/libssh2.1.dylib' (no such file), '/usr/local/lib/libssh2.1.dylib' (no such file), '/usr/lib/libssh2.1.dylib' (no such file, not in dyld cache)
(terminated at launch; ignore backtrace)

Thread 0 Crashed:
0   dyld                          	       0x1a5c0d118 __abort_with_payload + 8
1   dyld                          	       0x1a5c18d7c abort_with_payload_wrapper_internal + 104
2   dyld                          	       0x1a5c18db0 abort_with_payload + 16
3   dyld                          	       0x1a5ba48a8 dyld4::halt(char const*) + 328
4   dyld                          	       0x1a5ba1590 dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*) + 4184
5   dyld                          	       0x1a5b9fe18 start + 1964

Thread 0 crashed with ARM Thread State (64-bit):
    x0: 0x0000000000000006   x1: 0x0000000000000001   x2: 0x000000016fb1a920   x3: 0x000000000000007d
    x4: 0x000000016fb1a520   x5: 0x0000000000000000   x6: 0x0000000000000000   x7: 0x0000000000000b80
    x8: 0x0000000000000020   x9: 0x0000000000000009  x10: 0x0000000000000001  x11: 0x000000000000000a
   x12: 0x0000000000000000  x13: 0x0000000000000037  x14: 0x0000000000000004  x15: 0x0000000000008000
   x16: 0x0000000000000209  x17: 0x00000001a5b9d35c  x18: 0x0000000000000000  x19: 0x0000000000000000
   x20: 0x000000016fb1a520  x21: 0x000000000000007d  x22: 0x000000016fb1a920  x23: 0x0000000000000001
   x24: 0x0000000000000006  x25: 0x00000002013c1100  x26: 0x0000000000000000  x27: 0x0000000000000000
   x28: 0x0000000000000000   fp: 0x000000016fb1a4f0   lr: 0x00000001a5c18d7c
    sp: 0x000000016fb1a4b0   pc: 0x00000001a5c0d118 cpsr: 0x00001000
   far: 0x000000010526c000  esr: 0x56000080  Address size fault

Binary Images:
       0x1002e4000 -        0x103687fff com.tji.galaxy-slicer (1.0.0-alpha2) <d8dff0e4-8fd8-367b-a108-36d28c92fabf> /Applications/GalaxySlicer.app/Contents/MacOS/GalaxySlicer
       0x1a5b9a000 -        0x1a5c28553 dyld (*) <2237410f-d39c-30ce-9a94-13aacb66b766> /usr/lib/dyld

External Modification Summary:
  Calls made by other processes targeting this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by this process:
    task_for_pid: 0
    thread_create: 0
    thread_set_state: 0
  Calls made by all processes on this machine:
    task_for_pid: 2
    thread_create: 0
    thread_set_state: 0

VM Region Summary:
ReadOnly portion of Libraries: Total=878.7M resident=0K(0%) swapped_out_or_unallocated=878.7M(100%)
Writable regions: Total=8752K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8752K(100%)

                                VIRTUAL   REGION 
REGION TYPE                        SIZE    COUNT (non-coalesced) 
===========                     =======  ======= 
STACK GUARD                       56.0M        1 
Stack                             8176K        1 
VM_ALLOCATE                         16K        1 
__DATA                            1019K        3 
__DATA_CONST                      2102K        2 
__DATA_DIRTY                         7K        1 
__LINKEDIT                       826.5M        2 
__TEXT                            52.2M        2 
dyld private memory                272K        2 
===========                     =======  ======= 
TOTAL                            946.0M       15 

-----------
Full Report
-----------

{"app_name":"GalaxySlicer","timestamp":"2023-08-01 21:14:18.00 +0800","app_version":"1.0.0-alpha2","slice_uuid":"d8dff0e4-8fd8-367b-a108-36d28c92fabf","build_version":"","platform":1,"bundleID":"com.tji.galaxy-slicer","share_with_app_devs":0,"is_first_party":0,"bug_type":"309","os_version":"macOS 13.4.1 (22F770820d)","roots_installed":0,"name":"GalaxySlicer","incident_id":"BC7A4845-2EB5-4461-A653-FDF547149D89"}
{
  "uptime" : 590000,
  "procRole" : "Background",
  "version" : 2,
  "userID" : 501,
  "deployVersion" : 210,
  "modelCode" : "Mac14,3",
  "coalitionID" : 53747,
  "osVersion" : {
    "train" : "macOS 13.4.1",
    "build" : "22F770820d",
    "releaseType" : "User"
  },
  "captureTime" : "2023-08-01 21:14:18.5707 +0800",
  "incident" : "BC7A4845-2EB5-4461-A653-FDF547149D89",
  "pid" : 79628,
  "translated" : false,
  "cpuType" : "ARM-64",
  "roots_installed" : 0,
  "bug_type" : "309",
  "procLaunch" : "2023-08-01 21:14:17.7689 +0800",
  "procStartAbsTime" : 14360399161179,
  "procExitAbsTime" : 14360418385738,
  "procName" : "GalaxySlicer",
  "procPath" : "\/Applications\/GalaxySlicer.app\/Contents\/MacOS\/GalaxySlicer",
  "bundleInfo" : {"CFBundleShortVersionString":"1.0.0-alpha2","CFBundleIdentifier":"com.tji.galaxy-slicer"},
  "storeInfo" : {"deviceIdentifierForVendor":"2757E3DB-268E-5F0F-9CC1-61BA31FE0219","thirdParty":true},
  "parentProc" : "launchd",
  "parentPid" : 1,
  "coalitionName" : "com.tji.galaxy-slicer",
  "crashReporterKey" : "A3C956F4-9413-374D-1114-E0CC7FBD6F92",
  "codeSigningID" : "com.tji.galaxy-slicer",
  "codeSigningTeamID" : "",
  "codeSigningFlags" : 570425861,
  "codeSigningValidationCategory" : 10,
  "codeSigningTrustLevel" : 0,
  "sip" : "enabled",
  "exception" : {"codes":"0x0000000000000000, 0x0000000000000000","rawCodes":[0,0],"type":"EXC_CRASH","signal":"SIGABRT"},
  "termination" : {"code":1,"flags":518,"namespace":"DYLD","indicator":"Library missing","details":["(terminated at launch; ignore backtrace)"],"reasons":["Library not loaded: \/opt\/homebrew\/*\/libssh2.1.dylib","Referenced from: <D8DFF0E4-8FD8-367B-A108-36D28C92FABF> \/Applications\/GalaxySlicer.app\/Contents\/MacOS\/GalaxySlicer","Reason: tried: '\/opt\/homebrew\/*\/libssh2.1.dylib' (no such file), '\/System\/Volumes\/Preboot\/Cryptexes\/OS\/opt\/homebrew\/*\/libssh2.1.dylib' (no such file), '\/opt\/homebrew\/*\/libssh2.1.dylib' (no such file), '\/usr\/local\/lib\/libssh2.1.dylib' (no such file), '\/usr\/lib\/libssh2.1.dylib' (no such file, not in dyld cache)"]},
  "extMods" : {"caller":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"system":{"thread_create":0,"thread_set_state":0,"task_for_pid":2},"targeted":{"thread_create":0,"thread_set_state":0,"task_for_pid":0},"warnings":0},
  "faultingThread" : 0,
  "threads" : [{"triggered":true,"id":9418344,"threadState":{"x":[{"value":6},{"value":1},{"value":6168881440},{"value":125},{"value":6168880416},{"value":0},{"value":0},{"value":2944},{"value":32},{"value":9},{"value":1},{"value":10},{"value":0},{"value":55},{"value":4},{"value":32768},{"value":521},{"value":7075386204,"symbolLocation":416,"symbol":"__simple_bprintf"},{"value":0},{"value":0},{"value":6168880416},{"value":125},{"value":6168881440},{"value":1},{"value":6},{"value":8610648320,"symbolLocation":0,"symbol":"gProcessInfo"},{"value":0},{"value":0},{"value":0}],"flavor":"ARM_THREAD_STATE64","lr":{"value":7075892604},"cpsr":{"value":4096},"fp":{"value":6168880368},"sp":{"value":6168880304},"esr":{"value":1442840704,"description":" Address size fault"},"pc":{"value":7075844376,"matchesCrashFrame":1},"far":{"value":4381392896}},"frames":[{"imageOffset":471320,"symbol":"__abort_with_payload","symbolLocation":8,"imageIndex":1},{"imageOffset":519548,"symbol":"abort_with_payload_wrapper_internal","symbolLocation":104,"imageIndex":1},{"imageOffset":519600,"symbol":"abort_with_payload","symbolLocation":16,"imageIndex":1},{"imageOffset":43176,"symbol":"dyld4::halt(char const*)","symbolLocation":328,"imageIndex":1},{"imageOffset":30096,"symbol":"dyld4::prepare(dyld4::APIs&, dyld3::MachOAnalyzer const*)","symbolLocation":4184,"imageIndex":1},{"imageOffset":24088,"symbol":"start","symbolLocation":1964,"imageIndex":1}]}],
  "usedImages" : [
  {
    "source" : "P",
    "arch" : "arm64",
    "base" : 4297998336,
    "CFBundleShortVersionString" : "1.0.0-alpha2",
    "CFBundleIdentifier" : "com.tji.galaxy-slicer",
    "size" : 54149120,
    "uuid" : "d8dff0e4-8fd8-367b-a108-36d28c92fabf",
    "path" : "\/Applications\/GalaxySlicer.app\/Contents\/MacOS\/GalaxySlicer",
    "name" : "GalaxySlicer"
  },
  {
    "source" : "P",
    "arch" : "arm64e",
    "base" : 7075373056,
    "size" : 582996,
    "uuid" : "2237410f-d39c-30ce-9a94-13aacb66b766",
    "path" : "\/usr\/lib\/dyld",
    "name" : "dyld"
  }
],
  "sharedCache" : {
  "base" : 7074709504,
  "size" : 3551657984,
  "uuid" : "f5b60d87-3ee7-3c74-8415-517f8103a187"
},
  "vmSummary" : "ReadOnly portion of Libraries: Total=878.7M resident=0K(0%) swapped_out_or_unallocated=878.7M(100%)\nWritable regions: Total=8752K written=0K(0%) resident=0K(0%) swapped_out=0K(0%) unallocated=8752K(100%)\n\n                                VIRTUAL   REGION \nREGION TYPE                        SIZE    COUNT (non-coalesced) \n===========                     =======  ======= \nSTACK GUARD                       56.0M        1 \nStack                             8176K        1 \nVM_ALLOCATE                         16K        1 \n__DATA                            1019K        3 \n__DATA_CONST                      2102K        2 \n__DATA_DIRTY                         7K        1 \n__LINKEDIT                       826.5M        2 \n__TEXT                            52.2M        2 \ndyld private memory                272K        2 \n===========                     =======  ======= \nTOTAL                            946.0M       15 \n",
  "legacyInfo" : {
  "threadTriggered" : {

  }
},
  "logWritingSignature" : "900a3a51971d6f9af6d8bdd2618135d2635e2e6f",
  "trialInfo" : {
  "rollouts" : [
    {
      "rolloutId" : "62c751b6bcb0435c2153fe92",
      "factorPackIds" : {
        "SIRI_UNDERSTANDING_ASR_ASSISTANT" : "649a1ff23c66a8254c4d3b9e",
        "SIRI_UNDERSTANDING_MORPHUN" : "63f00b1c06644d312600c7bd"
      },
      "deploymentId" : 240000269
    },
    {
      "rolloutId" : "60186475825c62000ccf5450",
      "factorPackIds" : {

      },
      "deploymentId" : 240000055
    }
  ],
  "experiments" : [

  ]
}
}

Model: Mac14,3, BootROM 8422.121.1, proc 8:4:4 processors, 16 GB, SMC 
Graphics: Apple M2, Apple M2, Built-In
Display: K4021U, 3840 x 2160 (2160p/4K UHD 1 - Ultra High Definition), Main, MirrorOff, Online
Display: Philips 222El, 1920 x 1080 (1080p FHD - Full High Definition), MirrorOff, Online
Memory Module: LPDDR5, Hynix
AirPort: spairport_wireless_card_type_wifi (0x14E4, 0x4388), wl0: Apr 15 2023 07:46:47 version 23.20.84.0.40.50.94 FWID 01-da21599e
Bluetooth: Version (null), 0 services, 0 devices, 0 incoming serial ports
Network Service: Ethernet, Ethernet, en0
Network Service: Wi-Fi, AirPort, en1
USB Device: USB31Bus
USB Device: USB31Bus
USB Device: Best USB Device
USB Device: USB31Bus
USB Device: USB2.0 Hub
USB Device: G1000 series
USB Device: USB Hub 2.0
USB Device: USB Composite Device
USB Device: USB Receiver
USB Device: USB3.0 Hub
USB Device: Dell D1000 USB3.0 Dock
Thunderbolt Bus: Mac mini, Apple Inc.
Thunderbolt Bus: Mac mini, Apple Inc.

**Desktop (please complete the following information):**
 - OS: macos
 - Version 13.4.1 (c) (22F770820d)

**Comment by fr3ak2402** [comment]
Please download the hotfix.

https://github.com/fr3ak2402/GalaxySlicer/releases/download/V1.0.0-alpha2/GalaxySlicer_V1.0.0-alpha2_Hotfix_Mac_arm64.zip
