### ISSUE TITLE
Auxilary fan does not start in K1 (version - alpha2)

### ISSUE THREAD

**Issue by kaushikbm** [fr3ak2402/GalaxySlicer#32]
For PLA I used auxiliary fan on layer 2. But the fan doesn't start as specified in the filament settings.

**Comment by hliebscher** [comment]
is fixt in Beta?

**Comment by fr3ak2402** [comment]
@kaushikbm 
Found the problem...

Please activate the following in the profile, currently this setting is not active and ensures that the slicer does not consider an AUX fan for this printer. 
![image](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/59596cf8-031d-455d-9e47-671b6f44b2a9)

After you have activated this setting, you can also control the speed of the aux fan under the filaments.
![image](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/9bbfd405-a79b-4a01-a2d3-8b6eaa5fee44)

If you can slice an object you will also find in the Gcode M106 P2
![image](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/e293cda8-0583-455d-b731-7db89184b6ee)

Can you maybe test this once on your Creality K1 and give me feedback if this fixed your problem?

**Comment by kaushikbm** [comment]
@fr3ak2402 Hey that worked ! Thanks a lot. The AUX part fan has it's GCODE in place. 

As K1 has one more rear exhaust fan, I guess that will require modifications in the GUI to implement.

**Comment by fr3ak2402** [comment]
@kaushikbm 
is the rear exhaust fan responsible for the air in the chamber?

So the K1 has the same number of fans as my BambuLab X1C?

In BambuLab this fan % value is set static in the filament start code... if you give me the GCode for the extra fan, then I can install that for the K1.... 

Would set the first static for you and extend the interface to the setting for the other fan...

**Comment by fr3ak2402** [comment]
@kaushikbm 

Gcode to set rear exhaust fan -> M106 P3 too?

**Comment by kaushikbm** [comment]
Yes the rear exhaust fan is for chamber. But it is not M106 P3

Here is the GCODE 

 M106 P1 <xxx>

**Comment by fr3ak2402** [comment]
Thanks for sharing the gcode.
So I have already adjusted the UI...

![Screenshot 2023-09-26 142456](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/ef62de53-4636-4fb8-b7f1-28cfd67c405d)

Now I build in that the value is written in the code.

**Comment by kaushikbm** [comment]
Superb !

**Comment by fr3ak2402** [comment]
@kaushikbm 

I saw in your Github bio that you are from India. Can you maybe translate GalaxySlicer into Indian language for us?

**Comment by kaushikbm** [comment]
I would like to contribute and definitely will give it a try.

**Comment by fr3ak2402** [comment]
@kaushikbm 

Cool, I will maintain in the wiki everything you need to know to be able to add a translation for GalaxySlicer.

**Comment by kaushikbm** [comment]
I'll be looking forward :)

**Comment by fr3ak2402** [comment]
I have implemented the possibility of controlling the speed for the Chamber fan. Still need to do some test to see that there are no problems with the BambuLab printer.

In the wiki I have created small tutorial for creating a translation and customizing a translation. Later I will add some more images.

You can find it under the following link: [Translation guide](https://github.com/fr3ak2402/GalaxySlicer/wiki/Translation-guide)

**Comment by kaushikbm** [comment]
Ok. I'll go thru and try to understand the steps.

**Comment by kaushikbm** [comment]
> @kaushikbm Found the problem...
........
> Can you maybe test this once on your Creality K1 and give me feedback if this fixed your problem?

It seemed to me that the problem was solved. As I was printing small parts it was not very important. With 1.0.0 beta it is still there. The M106 P2 S0 is in place but only to STOP the fan with S0. But it's missing from the layer where the fan is suppose to START with M106 P2 Sxxx

**Comment by fr3ak2402** [comment]
@kaushikbm 

![image](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/0cf6aba5-282f-457a-9e08-d0ae167ce441)

So if you set in the slicer that the cooling should start only from the 3 or 4 etc, then you have first P2 S0 and from the determine layer the fan etc is switched on.

![image](https://github.com/fr3ak2402/GalaxySlicer/assets/96239814/3875744d-9b13-40e7-be56-d2e24948e03a)

I have the aux fan set to 70% during printing. But only from layer 3.

I have uploaded my gcode, which I just created with the dev version.

[GalaxyCube_PLA_22m45s.zip](https://github.com/fr3ak2402/GalaxySlicer/files/12892964/GalaxyCube_PLA_22m45s.zip)

**Comment by kaushikbm** [comment]
Perfect ! So when are planning to release beta2 ? :)

These are my settings for the 1.0.0 beta
![image](https://github.com/fr3ak2402/GalaxySlicer/assets/5709898/9d0febb7-b8ec-4211-9fc5-4695fb050e58)

**Comment by fr3ak2402** [comment]
@kaushikbm 

Currently I am still working on a major problem that occurs with macOS users and makes the slicer from GUI unusable. I hope I can fix the problem this week. then I would start a release of beta2.

I have installed the Chamber Fan for the K1, I have uploaded the Gcode... now you also M106 P1 is written in the Gcode, so you can now set all fans.

[GalaxyCube_PLA_22m34s.zip](https://github.com/fr3ak2402/GalaxySlicer/files/13069761/GalaxyCube_PLA_22m34s.zip)

**Comment by kaushikbm** [comment]
> @kaushikbm
> 
> Currently I am still working on a major problem that occurs with macOS users and makes the slicer from GUI unusable. I hope I can fix the problem this week. then I would start a release of beta2.
> 
> I have installed the Chamber Fan for the K1, I have uploaded the Gcode... now you also M106 P1 is written in the Gcode, so you can now set all fans.
> 
> [GalaxyCube_PLA_22m34s.zip](https://github.com/fr3ak2402/GalaxySlicer/files/13069761/GalaxyCube_PLA_22m34s.zip)

Thanks for the file. I'll check it out.
