### ISSUE TITLE
Error on startup

### ISSUE THREAD

**Issue by TV-Technics** [fr3ak2402/GalaxySlicer#34]
I get this error when I try to run galaxy

![image](https://github.com/fr3ak2402/GalaxySlicer/assets/140437996/b15a6855-c059-41af-836f-d74ad573f631)

**Comment by fr3ak2402** [comment]
Which version did you download?

If you have made an update from the Alpha to the Alpha2, then you have to delete all folders in the AppData of your user, because we had changed the profile system.

Note: The Appdata folder is a hidden folder.
