### ISSUE TITLE
macOS GalaxySlicer.app is damaged and can't be opened

### ISSUE THREAD

**Issue by Rijswijker** [fr3ak2402/GalaxySlicer#38]
**Describe the bug**
After downloading GalaxySlicer I am not able to run the .app file.
macOS give an error "GalaxySlicer.app is damaged and can't be opened, you should move it to the Trash."
Redownloading make no sense, also downloading the first Alpha version results in the same error.

**Screenshots**
<img width="341" alt="image" src="https://github.com/fr3ak2402/GalaxySlicer/assets/4473594/8bde4598-0a98-4166-8efb-3dd0a0578f6d">

**Desktop (please complete the following information):**
 - OS: maxOS 13.5.1
 - Type: Mac mini M2 Pro

**Comment by Rijswijker** [comment]
Hadn't seen that you needed to run another command in the terminal ;-)
`sudo xattr -d com.apple.quarantine /Applications/GalaxySlicer.app`

**Comment by fr3ak2402** [comment]
No problem, I was just about to reply.
